USE [master]
GO
/****** Object:  Database [MiniShop]    Script Date: 10/01/2026 14:23:41 ******/
CREATE DATABASE [MiniShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiniShop', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\MiniShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiniShop_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\MiniShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MiniShop] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiniShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MiniShop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MiniShop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MiniShop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MiniShop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MiniShop] SET ARITHABORT OFF 
GO
ALTER DATABASE [MiniShop] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MiniShop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MiniShop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MiniShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MiniShop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MiniShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MiniShop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MiniShop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MiniShop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MiniShop] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MiniShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MiniShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MiniShop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MiniShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MiniShop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MiniShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MiniShop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MiniShop] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MiniShop] SET  MULTI_USER 
GO
ALTER DATABASE [MiniShop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MiniShop] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MiniShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MiniShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MiniShop] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MiniShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MiniShop] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [MiniShop] SET QUERY_STORE = ON
GO
ALTER DATABASE [MiniShop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MiniShop]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 10/01/2026 14:23:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 10/01/2026 14:23:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 10/01/2026 14:23:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 10/01/2026 14:23:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[OrderDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 10/01/2026 14:23:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[CategoryId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (getdate()) FOR [OrderDate]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([OrderId])
REFERENCES [dbo].[Orders] ([Id])
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([Id])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([Id])
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
USE [master]
GO
ALTER DATABASE [MiniShop] SET  READ_WRITE 
GO
