
CREATE DATABASE BATTLEGAME;
GO
USE BATTLEGAME;

CREATE TABLE Player(
Id INT IDENTITY PRIMARY KEY,
PlayerName NVARCHAR(100),
FullName NVARCHAR(100),
Age INT,
Level INT
);

CREATE TABLE Asset(
Id INT IDENTITY PRIMARY KEY,
AssetName NVARCHAR(100)
);

CREATE TABLE PlayerAsset(
Id INT IDENTITY PRIMARY KEY,
PlayerId INT,
AssetId INT,
FOREIGN KEY(PlayerId) REFERENCES Player(Id),
FOREIGN KEY(AssetId) REFERENCES Asset(Id)
);
